### ISSUE TITLE
cyan links??

### ISSUE THREAD

**Issue by davidwhogg** [AASJournals/AASTeX60#17]
When printed on a b/w printer, the urls, refs, etc, appear very light grey. Let's use navy for all these, or black.

**Comment by gregschwarz** [comment]
AASTeX v6 uses hyperref to control this and thus you have the option to make the link colors whatever you want. See here:

https://en.wikibooks.org/wiki/LaTeX/Hyperlinks#Customization

for details on how to customize this to what you want.

Greg

**Comment by augustfly** [comment]
@gregschwarz i'm not entirely sure that our support for hyperref makes it easier or harder for users to pass in hyperref options. I'll need to investigate if this is a documentation update or a latex fix required.

**Comment by augustfly** [comment]
`\hypersetup{}` appears to be fully supported by our latex template. i'm going to leave this open so I can test some users fancier markup of ADS bibtex in the PDF, which I think is something that is a build out of `hyperref` options. 

and because this just became a documentation issue.

btw "navy" isn't a legit latex color, man. :neutral_face:

**Comment by davidwhogg** [comment]
I just think cyan is very, very, very bad as a default. I may be alone.

**Comment by augustfly** [comment]
A few updates:

1. We are indeed forcing cyan on folks, overriding the hyperref defaults. These are the current defaults in aastex6.
    ```
    linkcolor=cyan,     % color of internal links
    citecolor=cyan,     % color of links to bibliography
    filecolor=cyan,  % color of file links
    urlcolor=cyan,      % color of external links
    ```
when the hyperref defaults would normally have been:
    ```
    linkcolor=red,     % color of internal links
    citecolor=green,     % color of links to bibliography
    filecolor=cyan,  % color of file links
    urlcolor= magenta,      % color of external links                              
    ``` 
I have no idea why we are doing this. See recommended changes below:

1. **We will definitely need to update our docs so that users pass `\hypersetup{}` and not attempt to use `\usepackage[]{hyperref}` to set options. In fact our template should just have a stub `\hypersetup{}` to pre-empt the problem.** 

1. Beyond moving past cyan, I can only suggest that we should revert to set them all equal to "blue" (0000ff), which matches the color of links (inter-text and external) in our production PDFs. Tweaking a new set of ([analogous](https://en.wikipedia.org/wiki/Analogous_colors)) colors for our PDFs seems beyond my skill set.

**Comment by granttremblay** [comment]
I want to second the comment from @davidwhogg that cyan is an odd and probably sub-optimal choice for default color. It prints really badly, IMO. 

Don't get me wrong, I'm really liking AASTeX 6 (thank you for your work on this!) - but I do override the `hyperref` options to be this: 

```
\usepackage[backref,breaklinks,colorlinks,citecolor=blue]{hyperref} 
\usepackage[all]{hypcap} 
\renewcommand*{\backref}[1]{[#1]}
```

The philosophy behind this choice is nicely described [here](http://www.astrobetter.com/blog/2014/09/29/latex-hyperref-and-emulateapj/).

**Comment by augustfly** [comment]
v6.1 (https://github.com/AASJournals/AASTeX60/commit/f888b19ddaa5373790134df8fcf091de9adf622e) update returns the default `citecolor` to blue. 

the docs also now reinforce our desire for authors to use `\hypersetup{}` and not reimport `hyperref`.

http://journals.aas.org/authors/aastex/aasguide61.html#hypertext_constructs
