### ISSUE TITLE
Any chance of updating to biber/biblatex?

### ISSUE THREAD

**Issue by michaelaye** [AASJournals/AASTeX60#45]
As `bst` is slowly dying out, I was wondering if there's any plan to add biber/biblatex compatibility to AASTeX?

**Comment by augustfly** [comment]
Well, I've thought about it; especially because of what we want in compiled reference sections -- see #2. I think moving people to biblatex needs a stimulant or a bribe. Like an entirely new manuscript preparation system where they don't have to think about the details of compilers and class files and style files. Where they'd get all that for free. Then we'd spend the cash to invest in biblatex.

**Comment by michaelaye** [comment]
Actually, I'm fighting currently with quite some stupid encoding probs with biblatex, something I didn't meet with bibtex recently. So maybe it's still too `young`? :/ Why can't we have nice things... Bibtex needs to be hacked for reverse chronological listings, and biblatex seems to be not robust enough for everyday's bibliographies. Maybe time to look at LuaTex? Apparently it has less encoding probs.

**Comment by augustfly** [comment]
We are going to continue to invest in bst for the near future, so I'm going to close this for now.
